# Site settings
name: Timothy B. Smith
title: 'Geek, coffee snob, and maker of stuff'
email: smith@ttimsmith.com
description: 'Tim Smith is a geek, coffee snob, and maker of stuff in Oceanside, California.'
url: https://ttimsmith.com

twitter: https://twitter.com/smithtimmytim
micro-blog: https://micro.blog/smith
github: https://github.com/smithtimmytim
flickr: https://www.flickr.com/photos/smithtimmytim/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
permalink: /:year/:month/:title/
exclude: ['scss', 'README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'vendor']
sass:
  sass_dir: assets/stylesheets
  style: :compressed
timezone: America/Los_Angeles
livereload: true
