# Site settings
name: Timothy B. Smith
title: "Designer who codes, blabber mouth, and coffee addict."
email: smith@ttimsmith.com
description: "Tim Smith lives in beautiful St. Paul, Minnesota designing and building web applications. He made a podcasting CMS that powers Goodstuff FM and Relay FM."
url: https://ttimsmith.com

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:title/
exclude: ['scss', 'README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'vendor']
sass:
  sass_dir: assets/stylesheets
  style: :compressed
timezone: America/Chicago

# Collection
collections:
  work:
    output: true
    permalink: /portfolio/:title/
  microblog:
    output: true
    permalink: /microblog/:year/:month/:slug/
  talks:
    output: true
    permalink: /speaking/:title/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "microblog"
    values:
      layout: "microblog-post"
  -
    scope:
      path: ""
      type: "talks"
    values:
      layout: "talk"

#Misc
mapbox_token: pk.eyJ1IjoidHRpbXNtaXRoIiwiYSI6Imh3Z0piYTAifQ.smU_4_vde53ZOKHrrDzpeA
